Create engagements_consolidated CTE to remove a subquery
2x-data-ops/dataops pull request #168
Opened 2024-07-29 01:30 UTC by azwansyafiq-2X

2024-08-04 12:05 UTC, 2x-imransyafi requested changes
please remove subqueries in the mql_submission_email CTE.

2024-08-04 12:05 UTC, 2x-imransyafi commented on Clients/Terrasmart/Normalization Script/terrasmart_email_engagement_log.sql
> +),
For this CTE, you can do it like this,

`  SELECT
    download._sdc_sequence,
    download._prospectID,
    download._email,
    click._campaignID,
    click._utmcampaign,
    click._campaignCode,
    download._timestamp,
    download._description,
    --download._engagement,
    click._email_id,
    click.email_template_id,
    download._engagement,

  FROM clicks_downloads_timeline AS download
  JOIN clicks_downloads_timeline AS click
    ON download._prospectID = click._prospectID
    AND EXTRACT(DAY FROM download._timestamp) = EXTRACT(DAY FROM click._timestamp)
    AND download._rownum = click._rownum + 1`
    AND  click._engagement = 'Clicked'

WHERE download._engagement = 'Downloaded'

2024-08-08 04:04 UTC, azwansyafiq-2X commented on Clients/Terrasmart/Normalization Script/terrasmart_email_engagement_log.sql
> +),
I have made the changes based on your comment

2024-08-08 13:35 UTC, 2x-imransyafi requested changes

2024-08-08 13:35 UTC, 2x-imransyafi commented on Clients/Terrasmart/Normalization Script/terrasmart_email_engagement_log.sql
> +),
@azwansyafiq-2X 
AND click._engagement = 'Clicked'

should be in the JOIN condition so that you don't join the full `clicks_downloads_timeline`, it filters it before joining.

2024-08-09 07:31 UTC, azwansyafiq-2X commented
Okay, I have update the click engagement condition in JOIN

2024-08-09 09:58 UTC, 2x-imransyafi approved these changes

2024-08-09 09:58 UTC, merged