Update the hyland email engagement script into the gold standard
2x-data-ops/dataops pull request #171
Opened 2024-08-05 06:44 UTC by raaayden

Updating the hyland email engagement log into much better and optimized way.

[Wise Ticket Link](https://2x.wise-portal.com/request-summary.php?id=42151)

2024-08-06 12:48 UTC, 2x-imransyafi requested changes

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +  LEFT JOIN
JOIN table should in the same line as the JOIN statement, and the conditions should be below, and indented.
```
LEFT JOIN LI_ads_title
    ON LI_ads._adid = LI_ads_title._adid
    AND LI_ads.xx = LI_ads_title.xx
```

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +  WHERE
Formatting for filters in the WHERE clause,

```
WHERE xx
  AND xx
```

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +    `x-marketing.hyland_mysql.db_airtable_email_emea`
base table should be in the same line as the FROM statement. 

FROM `x-marketing.hyland_mysql.db_airtable_email_emea`

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +    `x-marketing.hyland_mysql.db_airtable_email_customermarketing`
base table should be in the same line as the FROM statement.

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +  ON email_open._leadid = email_click._leadid
JOIN condition need to be indented.

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +  NOT LIKE '%Email Unsubscribe Form%'
filters in where clause should follow this format:

```
WHERE xx
  AND xx
```

in this case:

```
WHERE primary_attribute_value NOT LIKE '%TEST 2X%'
  AND primary_attribute_value NOT LIKE '%Email Unsubscribe Form%'
```

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +    engagements_combined AS engagements
base table should be in the same line as the FROM statement.

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +    engagements._campaignID = CAST(airtable_info._id AS STRING)
Line 369 - 376, please follow JOIN formatting:

```
LEFT JOIN LI_ads_title
    ON LI_ads._adid = LI_ads_title._adid
    AND LI_ads.xx = LI_ads_title.xx
```

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +ON user.id = sfcampaign.ownerid;
LINE 389-392,  please follow JOIN formatting:

```
LEFT JOIN LI_ads_title
    ON LI_ads._adid = LI_ads_title._adid
    AND LI_ads.xx = LI_ads_title.xx
```

Also possible to remove the subquery in the LEFT JOIN?

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +  ON user.id = campaign.ownerid
LINE 415-418,  please follow JOIN formatting:

```
LEFT JOIN LI_ads_title
    ON LI_ads._adid = LI_ads_title._adid
    AND LI_ads.xx = LI_ads_title.xx
```

Also possible to remove the subquery in the LEFT JOIN?

2024-08-06 12:48 UTC, 2x-imransyafi commented on Clients/Hyland/Normalization Script/hyland_email_engagement_log.sql
> +ON email_aggregate._sfdccampaignid = campaign_aggregate._sfcampaignid
JOIN conditions should be indented.

2024-08-12 03:57 UTC, raaayden commented
This pull request is ready for another review.

2024-08-14 08:01 UTC, 2x-imransyafi approved these changes

2024-08-14 08:01 UTC, merged