Merge masttro-15 to main
2x-data-ops/dataops pull request #182
Opened 2024-08-14 09:03 UTC by izztsfn

This branch contains the script masttro_db_opportunity that adds two tables and also troubleshoots the cost field for cost per opportunity calculations

2024-08-19 07:17 UTC, nazzatul21 requested changes

2024-08-19 07:17 UTC, nazzatul21 commented on Clients/Masttro/Analytics Script/masttro_db_opportunity.sql
> +  CASE
Change to if statement , IF(_count_opp > 0 ,  SUM(_total_cost) OVER (PARTITION BY _date,_campaignName) / SUM(_count_opp) OVER (PARTITION BY _date,_campaignName), 0)
  AS _cost

2024-08-19 07:17 UTC, nazzatul21 commented on Clients/Masttro/Analytics Script/masttro_db_opportunity.sql
> +    WITH contacts AS (
make into single subquery, 

with contacts AS (
.
.
.
), ... AS (
.
.
.
), opportunity

2024-08-20 02:08 UTC, izztsfn commented on Clients/Masttro/Analytics Script/masttro_db_opportunity.sql
> +  CASE
Updated the CASE statement to IF

2024-08-20 02:08 UTC, izztsfn commented on Clients/Masttro/Analytics Script/masttro_db_opportunity.sql
> +    WITH contacts AS (
This is the old commit before the formatting. It has already been changed in the latest commit where ive updated the formatting

2024-08-20 02:21 UTC, nazzatul21 commented
Approve. Good

2024-08-20 02:22 UTC, nazzatul21 approved these changes

2024-08-20 02:22 UTC, merged