emburse email engagements log initial built
2x-data-ops/dataops pull request #209
Opened 2024-09-20 03:57 UTC by hafizasyraf72

2024-09-20 07:17 UTC, izztsfn commented
Also @hafizasyraf72 i believe email_engagements_log script should be placed in Normalization folder instead of Ads Performance. Please create a separate commit for this ya. Can ping me if you're unsure about this thanksss

2024-09-20 07:24 UTC, hafizasyraf72 commented
ohhh yaaa. my bad. thanks for the checking @izztsfn. I have replace it to the other folder named as "Normalization Script"

2024-09-23 02:55 UTC, izztsfn requested changes

2024-09-23 02:55 UTC, izztsfn commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +    SELECT _sdc_sequence,
@hafizasyraf72 indent the field under SELECT clause

2024-09-23 02:55 UTC, izztsfn commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +    WHERE _engagement <> 'Opened' AND _engagement = 'Clicked'
@hafizasyraf72 add new line for AND and ensure it is inline with the first condition

2024-09-23 02:55 UTC, izztsfn commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +  SELECT
@hafizasyraf72 reduce one indentation for the entire portion (SELECT onwards until end of the file)

2024-09-23 03:20 UTC, raaayden commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +    WHERE b._campaignID IS NULL AND b._leadid IS NULL
indent the AND on line 240

2024-09-24 02:40 UTC, hafizasyraf72 commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +    SELECT _sdc_sequence,
done indent the field under SELECT for each CTE
<img width="328" alt="Screenshot 2024-09-24 103807" src="https://github.com/user-attachments/assets/459d006b-3e0c-4354-abbd-53da7d3e72da">

2024-09-24 02:41 UTC, hafizasyraf72 commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +    WHERE _engagement <> 'Opened' AND _engagement = 'Clicked'
done amend this too

<img width="311" alt="image" src="https://github.com/user-attachments/assets/f7b85f8d-7236-4e39-ad65-af313b3127fd">

2024-09-24 02:42 UTC, hafizasyraf72 commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +  SELECT
this query after final CTE also had been reduce one indentation
<img width="299" alt="image" src="https://github.com/user-attachments/assets/ee35ac1d-489b-43e2-a6ef-3eb33b7e1b32">

2024-09-24 02:43 UTC, hafizasyraf72 commented on Clients/Emburse/Normalization Script/emburse_db_email_engagement_log.sql
> +    WHERE b._campaignID IS NULL AND b._leadid IS NULL
done indent at WHERE statement
<img width="161" alt="image" src="https://github.com/user-attachments/assets/f18bb8c6-6c5c-48a7-985f-690d539e2a8f">

2024-09-24 02:50 UTC, izztsfn approved these changes
Looks good!

2024-09-24 02:52 UTC, merged