FARO-1339-Velocity-Log-Changes
2x-data-ops/dataops pull request #210
Opened 2024-09-23 03:29 UTC by raaayden

made changes to the velocity log to incorporate member data

2024-09-24 02:29 UTC, izztsfn requested changes
@raaayden the formatting looks good. Just need to update the Create statements to use Replace instead for best practices. Thankssss

2024-09-24 02:29 UTC, izztsfn commented on Clients/FARO/Analytics Script/velocity/faro_velocity_log.sql
>  CREATE OR REPLACE TABLE `x-marketing.faro.db_activity_log` AS
Replace with Insert statement instead

2024-09-24 02:29 UTC, izztsfn commented on Clients/FARO/Analytics Script/velocity/faro_velocity_log.sql
> +CREATE OR REPLACE TABLE `x-marketing.faro.db_member_log` AS
Replace with Insert statement instead

2024-09-24 02:29 UTC, izztsfn commented on Clients/FARO/Analytics Script/velocity/faro_velocity_log.sql
>  CREATE OR REPLACE TABLE `x-marketing.faro.db_velocity_log` AS
Replace with Insert statement instead

2024-09-24 02:29 UTC, izztsfn commented on Clients/FARO/Analytics Script/velocity/faro_velocity_log.sql
> +CREATE OR REPLACE TABLE `x-marketing.faro.db_velocity_recent` AS
Replace with Insert statement instead

2024-09-24 02:29 UTC, izztsfn commented on Clients/FARO/Analytics Script/velocity/faro_velocity_log.sql
> +CREATE OR REPLACE TABLE `x-marketing.faro.db_member_stat` AS
Replace with Insert statement instead

2024-09-24 07:25 UTC, raaayden commented
hello @izztsfn  i have updated the script can you please check it again 👍

2024-09-25 02:15 UTC, izztsfn approved these changes
Looks good!

2024-09-25 02:15 UTC, merged