Initial build for data catalog script
2x-data-ops/dataops pull request #213
Opened 2024-09-24 07:11 UTC by meoflaxz

2024-09-25 02:49 UTC, izztsfn requested changes
Just some formatting changes to make

2024-09-25 02:49 UTC, izztsfn commented on Data_Catalog/data_catalog.sql
> +CREATE OR REPLACE TABLE `x-marketing.data_catalog.data_catalog` AS
Use Insert statement instead of Create

2024-09-25 02:49 UTC, izztsfn commented on Data_Catalog/data_catalog.sql
> +  WITH column_name AS (
Avoid using nested CTE

2024-09-25 02:49 UTC, izztsfn commented on Data_Catalog/data_catalog.sql
> +  WITH hubspot_source AS (
create a separated CTE to combine all of the CRMs to avoid subquerying

2024-09-25 10:20 UTC, meoflaxz commented
As per latest commit: https://github.com/2x-data-ops/dataops/pull/213/commits/a38efa8af4211e0af3df7be94cd5bc34643d9648

Fixed:
1. Remove both nested CTE
2. Now use INSERT statement instead of CREATE OR REPLACE 

Added:
1. Changed column naming convention
2. Table now has partitioning (table_created) and clustering (_table, _client_name, _crm_source) specs

@izztsfn

2024-09-26 02:41 UTC, izztsfn approved these changes
LGTM. I learned a lot from this script also. Keep up the good work! @meoflaxz

2024-09-26 02:42 UTC, merged